/*
 * This Java source file was generated by the Gradle 'init' task.
 *  Zach Walters and Nathanael Smith -- December 8
 *  Ian Rodriguez and Nathanael Smith -- December 13
 */

package testApplication;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTestComplex {
    @Test void nullError_1() {
        LibraryComplex classUnderTest = new LibraryComplex();
        assertEquals("3", classUnderTest.nullError_1(3), "nullError should return 'true'");
        assertEquals("", classUnderTest.nullError_1(null), "nullError should return 'true'");
        fail();
    }
    @Test void compareError_1() {
        LibraryComplex classUnderTest = new LibraryComplex();
        assertTrue(classUnderTest.compareError_1(1), "compareError should return 'true'");
        assertTrue(classUnderTest.compareError_1(2), "compareError should return 'true'");
        assertTrue(classUnderTest.compareError_1(3), "compareError should return 'true'");
        assertTrue(classUnderTest.compareError_1(4), "compareError should return 'true'");
        assertTrue(classUnderTest.compareError_1(5), "compareError should return 'true'");
        fail();
    }
    @Test void arithmeticError_1() {
        LibraryComplex classUnderTest = new LibraryComplex();
        assertTrue(classUnderTest.arithmeticError_1(1), "arithmeticError should return 'true'");
        assertTrue(classUnderTest.arithmeticError_1(2), "arithmeticError should return 'true'");
        assertTrue(classUnderTest.arithmeticError_1(3), "arithmeticError should return 'true'");
        assertTrue(classUnderTest.arithmeticError_1(4), "arithmeticError should return 'true'");
        fail();
    }
    @Test void bitwiseError_1() {
        LibraryComplex classUnderTest = new LibraryComplex();
        assertTrue(classUnderTest.bitwiseError_1(1), "boolError should return 'true'");
        assertTrue(classUnderTest.bitwiseError_1(2), "boolError should return 'true'");
        assertTrue(classUnderTest.bitwiseError_1(3), "boolError should return 'true'");
        fail();
    }
    @Test void negationError_1() {
        LibraryComplex classUnderTest = new LibraryComplex();
        assertTrue(classUnderTest.negationError_1(1), "deleteLineError should return 'true'");
        assertTrue(classUnderTest.negationError_1(2), "deleteLineError should return 'true'");
        assertTrue(classUnderTest.negationError_1(3), "deleteLineError should return 'true'");
        assertTrue(classUnderTest.negationError_1(4), "deleteLineError should return 'true'");
        assertTrue(classUnderTest.negationError_1(5), "deleteLineError should return 'true'");
        assertTrue(classUnderTest.negationError_1(6), "deleteLineError should return 'true'");
        assertTrue(classUnderTest.negationError_1(7), "deleteLineError should return 'true'");
        assertTrue(classUnderTest.negationError_1(8), "deleteLineError should return 'true'");
        assertTrue(classUnderTest.negationError_1(9), "deleteLineError should return 'true'");
        fail();
    }
    @Test void deleteLineError_1() {
        LibraryComplex classUnderTest = new LibraryComplex();
        assertTrue(classUnderTest.deleteLineError_1(1), "deleteLineError should return 'true'");
        assertTrue(classUnderTest.deleteLineError_1(2), "deleteLineError should return 'true'");
        assertTrue(classUnderTest.deleteLineError_1(3), "deleteLineError should return 'true'");
        assertTrue(classUnderTest.deleteLineError_1(4), "deleteLineError should return 'true'");
        assertTrue(classUnderTest.deleteLineError_1(5), "deleteLineError should return 'true'");
        assertTrue(classUnderTest.deleteLineError_1(6), "deleteLineError should return 'true'");
        fail();
    }

}

