/*
 * This Java source file was generated by the Gradle 'init' task.
 *  Zach Walters and Nathanael Smith worked on this 12/8
 */
package testApplication;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void nullError() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.nullError(), "nullError should return 'true'");
        fail();
    }
    @Test void compareError() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.compareError(), "compareError should return 'true'");
        fail();
    }
    @Test void arithmeticError() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.arithmeticError(), "arithmeticError should return 'true'");
        fail();
    }
    @Test void boolError() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.boolError(), "boolError should return 'true'");
        fail();
    }
    @Test void deleteLineError() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.deleteLineError(), "deleteLineError should return 'true'");
        fail();
    }
    @Test void ifElseIfError() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.ifElseIfError(), "ifElseIfError should return 'true'");
        fail();
    }
}







