/*
 * This Java source file was generated by the Gradle 'init' task.
 *  Zach Walters and Nathanael Smith -- December 8
 *  Ian Rodriguez and Nathanael Smith -- December 13
 */

/////  Ideas  /////
// operator switch
// ... compare operator (==, &&, ||, <, >, etc.)
// ... arithmetic operator (+, -, /, *, etc.)
// ... bitwise operator ( &, |, ^, etc.)
// ... negation of variable (!var)
// delete erroneous line
// "if" vs "else if"
//  .
//  NEED MORE

package testApplication;

public class LibrarySimple {

    public String nullError_1(Interger number) {
        // The solution should be the following:
        // String success = new String();
        // if (number != number){
        //    success = number.toString();
        // }
        String success = number.toString();
        return success;
    }

    public boolean compareError_1() {
        int a = 3;
        int b = 4;
        // could be a <= b or a < b
        return a > b;
    }

    public boolean arithmeticError_1() {
        int a = 13;
        int b = 7;
        // should be a * b
        int c = a + b;
        return c == 91;
    }

    public boolean bitwiseError_1() {
        int a = 5;
        int b = 3;
        // should be a | b
        int c = (a & b);
        return c == 7;
    }

    public boolean negationError_1(){
        boolean x = false;
        // should be  !x
        if (x) {
            return true;
        }
        else {
            return false;
        }
    }

    public boolean deleteLineError_1() {
        int a = 2;
        int b = 3;
        int c = 5;
        // Should delete next line
        c += a + b;
        return c == 5;
    }

}


//// Extra code for safe keeping
//    public boolean nullError() {
//        Integer value = null;
//        boolean success = true;
//        int a = 5;
//        int b = 10;
//        int c = 15;
//        success = (value == c);
//        return success;
//    }
//
//    public boolean ifElseIfError() {
//        boolean result = false;
//        if (true) {
//            result = !result;
//        }
//        // Should not flip result again
//        if (true) {
//            result = !result;
//        }
//        return result;
//    }