/*
 * This Java source file was generated by the Gradle 'init' task.
 *  Nathanael Smith -- December 14
 */

package testApplication;

public class LibraryComplex {

    public String nullError_1(Interger number) {
        // The solution should be the following:
        // String success = new String();
        // if (number != number){
        //    success = number.toString();
        // }
        String success = number.toString();
        return success;
    }

    public boolean compareError_1(int t) {
        // This function is contrived to fail whenever t%5 == 0.
        // There are 5 tests in LibraryTestComplex
        t = t % 5;
        int a = 3;
        int b = 4;
        boolean c = false;

        if (t == 0){
            // could be a <= b or a < b
            c = a > b;
        }
        else if (t == 1){
            c = a < b;
        }
        else if (t == 2){
            c = a < b;
        }
        else if (t == 3){
            c = a < b;
        }
        else if (t == 4) {
            c = a < b;
        }
        return c;
    }

    public boolean arithmeticError_1() {
        int a = 13;
        int b = 7;
        // should be a * b
        int c = a + b;
        return c == 91;
    }

    public boolean bitwiseError_1() {
        int a = 5;
        int b = 3;
        // should be a | b
        int c = (a & b);
        return c == 7;
    }

    public boolean negationError_1(){
        boolean x = false;
        // should be  !x
        if (x) {
            return true;
        }
        else {
            return false;
        }
    }

    public boolean deleteLineError_1() {
        int a = 2;
        int b = 3;
        int c = 5;
        // Should delete next line
        c += a + b;
        return c == 5;
    }

}

