/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testApplication;

public class Library {

    public boolean someLibraryMethod() {
        Integer value = null;
        boolean success = true;
        int a = 5;
        int b = 10;
        int c = 15;
        success = (value == c);
        return success;
    }
}
